In [1]:
!pip install -q --no-index torch-scatter -f https://data.pyg.org/whl/torch-1.8.1+cu111.html
!pip install -q --no-index torch-sparse -f https://data.pyg.org/whl/torch-1.8.1+cu111.html
!pip install -q --no-index torch-cluster -f https://data.pyg.org/whl/torch-1.8.1+cu111.html
!pip install -q --no-index torch-spline-conv -f https://data.pyg.org/whl/torch-1.8.1+cu111.html
!pip install -q torch-geometric

In [4]:
!pip install -q autogl==0.3.1

In [1]:
import yaml
import random
import torch.backends.cudnn
import numpy as np
from autogl.datasets import build_dataset_from_name
from autogl.solver import AutoNodeClassifier
from autogl.module import Acc
from autogl.backend import DependentBackend

[2022-05-31 13:01:23] INFO (root/MainThread) PyTorch Lightning is not installed.
[2022-05-31 13:01:23] INFO (root/MainThread) Tensorflow is not installed.


In [58]:
if torch.cuda.is_available():
    torch.cuda.set_device(0)
seed = 123
# set random seed
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
if torch.cuda.is_available():
    torch.cuda.manual_seed(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

In [3]:
choices=[
            "cora",
            "pubmed",
            "citeseer",
            "coauthor_cs",
            "coauthor_physics",
            "amazon_computers",
            "amazon_photo",
        ] 
dataset_name = choices[0]
dataset = build_dataset_from_name(dataset_name)
label = dataset[0].nodes.data["y" if DependentBackend.is_pyg() else "label"]
num_classes = len(np.unique(label.numpy()))

In [27]:
dataset

In [4]:
spec = """ensemble:
  name: null
feature:
- name: NormalizeFeatures
hpo:
  max_evals: 10
  name: random
models:
- hp_space:
  - feasiblePoints: '2'
    parameterName: num_layers
    type: DISCRETE
  - cutFunc: lambda x:x[0] - 1
    cutPara:
    - num_layers
    length: 1
    maxValue:
    - 64
    minValue:
    - 16
    numericalType: INTEGER
    parameterName: hidden
    scalingType: LOG
    type: NUMERICAL_LIST
  - maxValue: 0.8
    minValue: 0.2
    parameterName: dropout
    scalingType: LINEAR
    type: DOUBLE
  - feasiblePoints:
    - leaky_relu
    - relu
    - elu
    - tanh
    parameterName: act
    type: CATEGORICAL
  name: gcn-model
trainer:
  hp_space:
  - maxValue: 300
    minValue: 100
    parameterName: max_epoch
    scalingType: LINEAR
    type: INTEGER
  - maxValue: 30
    minValue: 10
    parameterName: early_stopping_round
    scalingType: LINEAR
    type: INTEGER
  - maxValue: 0.05
    minValue: 0.005
    parameterName: lr
    scalingType: LOG
    type: DOUBLE
  - maxValue: 0.001
    minValue: 0.0001
    parameterName: weight_decay
    scalingType: LOG
    type: DOUBLE"""

In [5]:
configs = yaml.load(spec, Loader=yaml.FullLoader)
configs["hpo"]["name"] = "tpe"
configs["hpo"]["max_evals"] = 20
configs['device'] = 'cpu'
configs

{'ensemble': {'name': None},
 'feature': [{'name': 'NormalizeFeatures'}],
 'hpo': {'max_evals': 20, 'name': 'tpe'},
 'models': [{'hp_space': [{'feasiblePoints': '2',
     'parameterName': 'num_layers',
     'type': 'DISCRETE'},
    {'cutFunc': 'lambda x:x[0] - 1',
     'cutPara': ['num_layers'],
     'length': 1,
     'maxValue': [64],
     'minValue': [16],
     'numericalType': 'INTEGER',
     'parameterName': 'hidden',
     'scalingType': 'LOG',
     'type': 'NUMERICAL_LIST'},
    {'maxValue': 0.8,
     'minValue': 0.2,
     'parameterName': 'dropout',
     'scalingType': 'LINEAR',
     'type': 'DOUBLE'},
    {'feasiblePoints': ['leaky_relu', 'relu', 'elu', 'tanh'],
     'parameterName': 'act',
     'type': 'CATEGORICAL'}],
   'name': 'gcn-model'}],
 'trainer': {'hp_space': [{'maxValue': 300,
    'minValue': 100,
    'parameterName': 'max_epoch',
    'scalingType': 'LINEAR',
    'type': 'INTEGER'},
   {'maxValue': 30,
    'minValue': 10,
    'parameterName': 'early_stopping_round',


In [6]:
autoClassifier = AutoNodeClassifier.from_config(configs)

[2022-05-31 09:10:20] WARNING (root/MainThread) Ignore passed dec since enc is a whole model


In [7]:
import logging
# logging.Logger.manager.loggerDict
logging.getLogger().isEnabledFor(logging.WARNING)

True

In [8]:
logging.getLogger().addFilter(lambda s: "Ignore passed dec since enc is a whole model" not in s.getMessage())

In [9]:
# train
if dataset_name in ["cora", "citeseer", "pubmed"]:
    autoClassifier.fit(dataset, time_limit=3600, evaluation_method=[Acc])
else:
    autoClassifier.fit(
        dataset,
        time_limit=3600,
        evaluation_method=[Acc],
        seed=seed,
        train_split=20 * num_classes,
        val_split=30 * num_classes,
        balanced=False,
    )

[2022-05-31 09:10:20] INFO (NodeClassifier/MainThread) Use the default train/val/test ratio in given dataset
HPO Search Phase:



  0%|          | 0/20 [00:00<?, ?it/s]

[2022-05-31 09:10:20] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.073220 seconds
[2022-05-31 09:10:20] INFO (hyperopt.tpe/MainThread) TPE using 0 trials
[2022-05-31 09:10:25] INFO (HPO/MainThread) Parameter: {'trainer': {'max_epoch': 275, 'early_stopping_round': 15, 'lr': 0.014164148516981535, 'weight_decay': 0.0006419292885702267}, 'encoder': {'num_layers': 2, 'hidden': [20], 'dropout': 0.7736718727304612, 'act': 'relu'}, 'decoder': {}} acc: 0.808 higher_better


  5%|▌         | 1/20 [00:05<01:42,  5.38s/it]

[2022-05-31 09:10:25] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.002169 seconds
[2022-05-31 09:10:25] INFO (hyperopt.tpe/MainThread) TPE using 1/1 trials with best loss -0.808000
[2022-05-31 09:10:30] INFO (HPO/MainThread) Parameter: {'trainer': {'max_epoch': 271, 'early_stopping_round': 27, 'lr': 0.04323531162686548, 'weight_decay': 0.00032750370206197614}, 'encoder': {'num_layers': 2, 'hidden': [34], 'dropout': 0.5387337145728119, 'act': 'tanh'}, 'decoder': {}} acc: 0.81 higher_better


 10%|█         | 2/20 [00:10<01:35,  5.28s/it]

[2022-05-31 09:10:30] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.002226 seconds
[2022-05-31 09:10:30] INFO (hyperopt.tpe/MainThread) TPE using 2/2 trials with best loss -0.810000
[2022-05-31 09:10:40] INFO (HPO/MainThread) Parameter: {'trainer': {'max_epoch': 248, 'early_stopping_round': 24, 'lr': 0.008380456024063966, 'weight_decay': 0.0005448111439034048}, 'encoder': {'num_layers': 2, 'hidden': [57], 'dropout': 0.6190133128966635, 'act': 'elu'}, 'decoder': {}} acc: 0.798 higher_better


 15%|█▌        | 3/20 [00:20<02:04,  7.30s/it]

[2022-05-31 09:10:40] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.072070 seconds
[2022-05-31 09:10:40] INFO (hyperopt.tpe/MainThread) TPE using 3/3 trials with best loss -0.810000
[2022-05-31 09:10:49] INFO (HPO/MainThread) Parameter: {'trainer': {'max_epoch': 145, 'early_stopping_round': 12, 'lr': 0.014367433484656238, 'weight_decay': 0.0007780131308915355}, 'encoder': {'num_layers': 2, 'hidden': [33], 'dropout': 0.46075834313659675, 'act': 'leaky_relu'}, 'decoder': {}} acc: 0.806 higher_better


 20%|██        | 4/20 [00:28<02:04,  7.81s/it]

[2022-05-31 09:10:49] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.002459 seconds
[2022-05-31 09:10:49] INFO (hyperopt.tpe/MainThread) TPE using 4/4 trials with best loss -0.810000
[2022-05-31 09:10:55] INFO (HPO/MainThread) Parameter: {'trainer': {'max_epoch': 172, 'early_stopping_round': 24, 'lr': 0.01775340371828432, 'weight_decay': 0.0004137851759696565}, 'encoder': {'num_layers': 2, 'hidden': [17], 'dropout': 0.2213423476284735, 'act': 'leaky_relu'}, 'decoder': {}} acc: 0.8 higher_better


 25%|██▌       | 5/20 [00:35<01:50,  7.34s/it]

[2022-05-31 09:10:55] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.002118 seconds
[2022-05-31 09:10:55] INFO (hyperopt.tpe/MainThread) TPE using 5/5 trials with best loss -0.810000
[2022-05-31 09:10:57] INFO (HPO/MainThread) Parameter: {'trainer': {'max_epoch': 296, 'early_stopping_round': 14, 'lr': 0.010464404616277961, 'weight_decay': 0.0006489247197634635}, 'encoder': {'num_layers': 2, 'hidden': [28], 'dropout': 0.39310272394227536, 'act': 'leaky_relu'}, 'decoder': {}} acc: 0.772 higher_better


 30%|███       | 6/20 [00:37<01:18,  5.62s/it]

[2022-05-31 09:10:58] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.002145 seconds
[2022-05-31 09:10:58] INFO (hyperopt.tpe/MainThread) TPE using 6/6 trials with best loss -0.810000
[2022-05-31 09:11:04] INFO (HPO/MainThread) Parameter: {'trainer': {'max_epoch': 143, 'early_stopping_round': 14, 'lr': 0.010650032489608982, 'weight_decay': 0.000663680282784584}, 'encoder': {'num_layers': 2, 'hidden': [28], 'dropout': 0.7003349925844391, 'act': 'leaky_relu'}, 'decoder': {}} acc: 0.788 higher_better


 35%|███▌      | 7/20 [00:44<01:17,  5.98s/it]

[2022-05-31 09:11:04] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.002150 seconds
[2022-05-31 09:11:04] INFO (hyperopt.tpe/MainThread) TPE using 7/7 trials with best loss -0.810000
[2022-05-31 09:11:13] INFO (HPO/MainThread) Parameter: {'trainer': {'max_epoch': 209, 'early_stopping_round': 19, 'lr': 0.011197767361844222, 'weight_decay': 0.00020749262497848976}, 'encoder': {'num_layers': 2, 'hidden': [43], 'dropout': 0.2981524710825553, 'act': 'leaky_relu'}, 'decoder': {}} acc: 0.8 higher_better


 40%|████      | 8/20 [00:52<01:20,  6.72s/it]

[2022-05-31 09:11:13] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.210784 seconds
[2022-05-31 09:11:13] INFO (hyperopt.tpe/MainThread) TPE using 8/8 trials with best loss -0.810000
[2022-05-31 09:11:27] INFO (HPO/MainThread) Parameter: {'trainer': {'max_epoch': 139, 'early_stopping_round': 21, 'lr': 0.008329372188913789, 'weight_decay': 0.0003416743789200837}, 'encoder': {'num_layers': 2, 'hidden': [47], 'dropout': 0.772354437743668, 'act': 'elu'}, 'decoder': {}} acc: 0.812 higher_better


 45%|████▌     | 9/20 [01:06<01:39,  9.03s/it]

[2022-05-31 09:11:27] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.002258 seconds
[2022-05-31 09:11:27] INFO (hyperopt.tpe/MainThread) TPE using 9/9 trials with best loss -0.812000
[2022-05-31 09:11:31] INFO (HPO/MainThread) Parameter: {'trainer': {'max_epoch': 234, 'early_stopping_round': 14, 'lr': 0.026261961722747286, 'weight_decay': 0.00022772514284791068}, 'encoder': {'num_layers': 2, 'hidden': [27], 'dropout': 0.6733970935179454, 'act': 'tanh'}, 'decoder': {}} acc: 0.808 higher_better


 50%|█████     | 10/20 [01:10<01:14,  7.44s/it]

[2022-05-31 09:11:31] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.002176 seconds
[2022-05-31 09:11:31] INFO (hyperopt.tpe/MainThread) TPE using 10/10 trials with best loss -0.812000
[2022-05-31 09:11:37] INFO (HPO/MainThread) Parameter: {'trainer': {'max_epoch': 123, 'early_stopping_round': 18, 'lr': 0.01535474236769196, 'weight_decay': 0.0002284789225749846}, 'encoder': {'num_layers': 2, 'hidden': [35], 'dropout': 0.7510614463083309, 'act': 'relu'}, 'decoder': {}} acc: 0.808 higher_better


 55%|█████▌    | 11/20 [01:17<01:04,  7.12s/it]

[2022-05-31 09:11:37] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.002185 seconds
[2022-05-31 09:11:37] INFO (hyperopt.tpe/MainThread) TPE using 11/11 trials with best loss -0.812000
[2022-05-31 09:11:40] INFO (HPO/MainThread) Parameter: {'trainer': {'max_epoch': 207, 'early_stopping_round': 13, 'lr': 0.01942450531837371, 'weight_decay': 0.00012061564841020534}, 'encoder': {'num_layers': 2, 'hidden': [27], 'dropout': 0.6259292229398846, 'act': 'relu'}, 'decoder': {}} acc: 0.788 higher_better


 60%|██████    | 12/20 [01:19<00:46,  5.81s/it]

[2022-05-31 09:11:40] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.002186 seconds
[2022-05-31 09:11:40] INFO (hyperopt.tpe/MainThread) TPE using 12/12 trials with best loss -0.812000
[2022-05-31 09:11:51] INFO (HPO/MainThread) Parameter: {'trainer': {'max_epoch': 171, 'early_stopping_round': 28, 'lr': 0.03549158537571108, 'weight_decay': 0.00022661131353553655}, 'encoder': {'num_layers': 2, 'hidden': [25], 'dropout': 0.718669523320584, 'act': 'tanh'}, 'decoder': {}} acc: 0.806 higher_better


 65%|██████▌   | 13/20 [01:31<00:52,  7.50s/it]

[2022-05-31 09:11:51] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.002321 seconds
[2022-05-31 09:11:51] INFO (hyperopt.tpe/MainThread) TPE using 13/13 trials with best loss -0.812000
[2022-05-31 09:11:58] INFO (HPO/MainThread) Parameter: {'trainer': {'max_epoch': 255, 'early_stopping_round': 27, 'lr': 0.02043881458310644, 'weight_decay': 0.00048699717768760175}, 'encoder': {'num_layers': 2, 'hidden': [61], 'dropout': 0.36096111833061617, 'act': 'elu'}, 'decoder': {}} acc: 0.802 higher_better


 70%|███████   | 14/20 [01:38<00:44,  7.38s/it]

[2022-05-31 09:11:58] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.002235 seconds
[2022-05-31 09:11:58] INFO (hyperopt.tpe/MainThread) TPE using 14/14 trials with best loss -0.812000
[2022-05-31 09:12:00] INFO (HPO/MainThread) Parameter: {'trainer': {'max_epoch': 230, 'early_stopping_round': 11, 'lr': 0.03103993551224613, 'weight_decay': 0.0005681761062960785}, 'encoder': {'num_layers': 2, 'hidden': [24], 'dropout': 0.7916001689098198, 'act': 'relu'}, 'decoder': {}} acc: 0.64 higher_better


 75%|███████▌  | 15/20 [01:40<00:28,  5.67s/it]

[2022-05-31 09:12:00] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.002414 seconds
[2022-05-31 09:12:00] INFO (hyperopt.tpe/MainThread) TPE using 15/15 trials with best loss -0.812000
[2022-05-31 09:12:02] INFO (HPO/MainThread) Parameter: {'trainer': {'max_epoch': 175, 'early_stopping_round': 12, 'lr': 0.005831198123075771, 'weight_decay': 0.000533267053767182}, 'encoder': {'num_layers': 2, 'hidden': [25], 'dropout': 0.6482605977600435, 'act': 'tanh'}, 'decoder': {}} acc: 0.67 higher_better


 80%|████████  | 16/20 [01:41<00:18,  4.53s/it]

[2022-05-31 09:12:02] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.002151 seconds
[2022-05-31 09:12:02] INFO (hyperopt.tpe/MainThread) TPE using 16/16 trials with best loss -0.812000
[2022-05-31 09:12:05] INFO (HPO/MainThread) Parameter: {'trainer': {'max_epoch': 271, 'early_stopping_round': 11, 'lr': 0.0063007186211922455, 'weight_decay': 0.00021769543732943851}, 'encoder': {'num_layers': 2, 'hidden': [38], 'dropout': 0.762405261949159, 'act': 'leaky_relu'}, 'decoder': {}} acc: 0.72 higher_better


 85%|████████▌ | 17/20 [01:44<00:12,  4.02s/it]

[2022-05-31 09:12:05] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.002283 seconds
[2022-05-31 09:12:05] INFO (hyperopt.tpe/MainThread) TPE using 17/17 trials with best loss -0.812000
[2022-05-31 09:12:13] INFO (HPO/MainThread) Parameter: {'trainer': {'max_epoch': 296, 'early_stopping_round': 29, 'lr': 0.04888395120644118, 'weight_decay': 0.0005673483312591375}, 'encoder': {'num_layers': 2, 'hidden': [47], 'dropout': 0.33748590865824124, 'act': 'tanh'}, 'decoder': {}} acc: 0.804 higher_better


 90%|█████████ | 18/20 [01:52<00:10,  5.18s/it]

[2022-05-31 09:12:13] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.002153 seconds
[2022-05-31 09:12:13] INFO (hyperopt.tpe/MainThread) TPE using 18/18 trials with best loss -0.812000
[2022-05-31 09:12:17] INFO (HPO/MainThread) Parameter: {'trainer': {'max_epoch': 293, 'early_stopping_round': 11, 'lr': 0.029907962636370397, 'weight_decay': 0.000526907062533777}, 'encoder': {'num_layers': 2, 'hidden': [34], 'dropout': 0.4846252384428438, 'act': 'relu'}, 'decoder': {}} acc: 0.802 higher_better


 95%|█████████▌| 19/20 [01:57<00:05,  5.10s/it]

[2022-05-31 09:12:18] INFO (hyperopt.tpe/MainThread) tpe_transform took 0.002316 seconds
[2022-05-31 09:12:18] INFO (hyperopt.tpe/MainThread) TPE using 19/19 trials with best loss -0.812000
[2022-05-31 09:12:28] INFO (HPO/MainThread) Parameter: {'trainer': {'max_epoch': 197, 'early_stopping_round': 27, 'lr': 0.009982900802243988, 'weight_decay': 0.0007904411595331108}, 'encoder': {'num_layers': 2, 'hidden': [19], 'dropout': 0.38351425365310265, 'act': 'tanh'}, 'decoder': {}} acc: 0.806 higher_better


100%|██████████| 20/20 [02:08<00:00,  6.42s/it]


[2022-05-31 09:12:28] INFO (HPO/MainThread) Best Parameter:
[2022-05-31 09:12:28] INFO (HPO/MainThread) Parameter: {'trainer': {'max_epoch': 139, 'early_stopping_round': 21, 'lr': 0.008329372188913789, 'weight_decay': 0.0003416743789200837}, 'encoder': {'num_layers': 2, 'hidden': [47], 'dropout': 0.772354437743668, 'act': 'elu'}, 'decoder': {}} acc: 0.812 higher_better


# KServe

In [4]:
import joblib
import copy
import dill

In [10]:
acf.dataset = None
autoClassifier = acf

In [11]:
with open('autoClassifier.dill', 'wb') as file:
    dill.dump(autoClassifier, file)

In [12]:
with open('autoClassifier.dill', 'rb') as file:
    acf = dill.load(file)

In [26]:
for m in acf.trained_models.values():
    print (type(m.encoder))

<class 'autogl.module.model.pyg.gcn.AutoGCN'>


In [13]:
acf.predict_proba(dataset)

[2022-05-31 13:02:22] INFO (NodeClassifier/MainThread) Ensemble argument on, will try using ensemble model.
[2022-05-31 13:02:22] WARNING (NodeClassifier/MainThread) Cannot use ensemble because no ensebmle module is given. Will use best model instead.


array([[0.17524756, 0.20365748, 0.16183828, ..., 0.09015678, 0.15732759,
        0.06911414],
       [0.0546177 , 0.03481817, 0.77426016, ..., 0.03831783, 0.02858152,
        0.02712895],
       [0.07899787, 0.121613  , 0.44402656, ..., 0.07093763, 0.07331976,
        0.02558529],
       ...,
       [0.14718598, 0.2669439 , 0.014981  , ..., 0.01907321, 0.256131  ,
        0.12125333],
       [0.05522497, 0.05555305, 0.05347392, ..., 0.14460424, 0.04363336,
        0.02152764],
       [0.05620539, 0.0667403 , 0.06415007, ..., 0.12279192, 0.05495729,
        0.02350215]], dtype=float32)

In [84]:
autoClassifier.predict_proba(dataset)

[2022-05-31 12:59:23] INFO (NodeClassifier/MainThread) Ensemble argument on, will try using ensemble model.
[2022-05-31 12:59:23] WARNING (NodeClassifier/MainThread) Cannot use ensemble because no ensebmle module is given. Will use best model instead.


array([[0.17524756, 0.20365748, 0.16183828, ..., 0.09015678, 0.15732759,
        0.06911414],
       [0.0546177 , 0.03481817, 0.77426016, ..., 0.03831783, 0.02858152,
        0.02712895],
       [0.07899787, 0.121613  , 0.44402656, ..., 0.07093763, 0.07331976,
        0.02558529],
       ...,
       [0.14718598, 0.2669439 , 0.014981  , ..., 0.01907321, 0.256131  ,
        0.12125333],
       [0.05522497, 0.05555305, 0.05347392, ..., 0.14460424, 0.04363336,
        0.02152764],
       [0.05620539, 0.0667403 , 0.06415007, ..., 0.12279192, 0.05495729,
        0.02350215]], dtype=float32)

In [30]:
from torch_geometric.datasets import (
    Amazon, Coauthor, Flickr, ModelNet,
    Planetoid, PPI, QM9, Reddit, TUDataset
)
import os

In [32]:
pyg_dataset = Planetoid('./datasets', "Cora")

Processing...
Done!


In [35]:
if hasattr(pyg_dataset, "__data_list__"):
    delattr(pyg_dataset, "__data_list__")
if hasattr(pyg_dataset, "_data_list"):
    delattr(pyg_dataset, "_data_list")

In [36]:
pyg_data = pyg_dataset[0]
pyg_data

Data(x=[2708, 1433], edge_index=[2, 10556], y=[2708], train_mask=[2708], val_mask=[2708], test_mask=[2708])

In [88]:
pyg_data.x.size()

torch.Size([2708, 1433])

In [40]:
type(pyg_data.x), pyg_data.x

(torch.Tensor,
 tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]))

In [41]:
type(pyg_data.y), pyg_data.y

(torch.Tensor, tensor([3, 4, 4,  ..., 3, 3, 3]))

In [104]:
x = getattr(pyg_data, 'train_mask')
type(x), x, x.size()

(torch.Tensor,
 tensor([ True,  True,  True,  ..., False, False, False]),
 torch.Size([2708]))

In [44]:
getattr(pyg_data, 'test_mask')

tensor([False, False, False,  ...,  True,  True,  True])

In [75]:
from autogl.data.graph import GeneralStaticGraphGenerator
from autogl.data import InMemoryStaticGraphSet

In [96]:
        static_graph = GeneralStaticGraphGenerator.create_homogeneous_static_graph(
            {
                'x': pyg_data.x,
                'y': pyg_data.y,
                'train_mask': getattr(pyg_data, 'train_mask'),
                'val_mask': getattr(pyg_data, 'val_mask'),
                'test_mask': getattr(pyg_data, 'test_mask')
            },
            pyg_data.edge_index
        )
    
dataset = InMemoryStaticGraphSet([static_graph])
dataset

In [63]:
!pip install pyTigerGraph

In [64]:
import pyTigerGraph as tg
conn = tg.TigerGraphConnection("http://35.230.92.92", graphname="Cora")

In [117]:
hp = {"batch_size": 64, "num_neighbors": 10, "num_hops": 2, "hidden_dim": 64,
      "num_layers": 2, "dropout": 0.6, "lr": 0.01, "l2_penalty": 5e-4}
infer_loader = conn.gds.neighborLoader(
                                v_in_feats=["x"],
                                v_out_labels=["y"],
                                output_format="PyG",
                                batch_size=hp["batch_size"],
                                num_neighbors=hp["num_neighbors"],
                                num_hops=hp["num_hops"],
                                shuffle=False)

In [118]:
input_nodes = [
      {"primary_id": 7, "type": "Paper"}, 
      {"primary_id": 999, "type": "Paper"}
    ]

data = infer_loader.fetch(input_nodes)
data

Data(edge_index=[2, 16], x=[15, 1433], y=[15], is_seed=[15], primary_id=[15])

In [120]:
data.edge_index

tensor([[ 7, 10, 13, 10, 12, 13,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8],
        [12,  8,  8, 13,  7, 10,  0,  1,  2,  9,  3,  6, 14,  5, 11,  4]])

In [113]:
type(data.x), data.x

(torch.Tensor,
 tensor([[0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         ...,
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]]))

In [87]:
data.x.size()

torch.Size([15, 1433])

In [69]:
type(data.y), data.y

(torch.Tensor, tensor([2, 2, 2, 2, 2, 3, 2, 2, 3, 2, 2, 2, 2, 2, 2]))

In [73]:
#getattr(data, 'train_mask')
x = torch.zeros(10, dtype=torch.bool)
type(x), x

(torch.Tensor,
 tensor([False, False, False, False, False, False, False, False, False, False]))

In [127]:
mask = torch.ones(data.x.size()[0], dtype=torch.bool)

static_graph = GeneralStaticGraphGenerator.create_homogeneous_static_graph(
    {
        'x': data.x.float(),
        'y': data.y,
        'train_mask': mask,
        'val_mask': mask,
        'test_mask': mask
    },
    data.edge_index
)
    
tg_dataset = InMemoryStaticGraphSet([static_graph])
tg_dataset

In [128]:
acf.predict(dataset)

[2022-05-31 17:16:19] INFO (NodeClassifier/MainThread) Ensemble argument on, will try using ensemble model.
[2022-05-31 17:16:19] WARNING (NodeClassifier/MainThread) Cannot use ensemble because no ensebmle module is given. Will use best model instead.


array([1, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2,
       2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 1, 1, 1, 5, 5, 5, 4,
       4, 1, 1, 3, 1, 1, 1, 6, 2, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 6, 6, 3, 0, 0,
       0, 0, 5, 0, 0, 0, 3, 0, 0, 6, 0, 6, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5,
       5, 5, 2, 2, 2, 4, 4, 4, 4, 3, 3, 2, 5, 5, 5, 5, 6, 5, 5, 5, 5, 3,
       4, 3, 0, 3, 1, 0, 0, 0, 6, 6, 6, 6, 6, 6, 6, 0, 0, 0, 0, 0, 0, 0,
       3, 3, 0, 3, 3, 3, 3, 3, 3, 0, 0, 3, 3, 3, 3, 0, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 4,
       6, 6, 5, 6, 6, 0, 5, 5, 5, 0, 5, 0, 4, 0, 3, 3, 3, 2, 3, 1, 3, 3,
       3, 3, 3, 3, 1, 3, 3, 4, 4, 4, 3, 3, 3, 3, 3,

In [129]:
#with torch.no_grad():

acf.predict(tg_dataset, inplaced = False, inplace=True)

[2022-05-31 17:16:20] INFO (NodeClassifier/MainThread) Ensemble argument on, will try using ensemble model.
[2022-05-31 17:16:20] WARNING (NodeClassifier/MainThread) Cannot use ensemble because no ensebmle module is given. Will use best model instead.


array([2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2, 3, 2, 2])

In [62]:
for k, v in autoClassifier.trained_models.items():
    print(k)
    print (type(v))
    print ('---')
    v = copy.deepcopy(v)

decoder: None
early_stopping_round: 21
encoder: <autogl.module.model.pyg.gcn.AutoGCN object at 0x7fd8ac8e3e50>
learning_rate: 0.008329372188913789
max_epoch: 139
optimizer: !!python/name:torch.optim.adam.Adam ''
trainer_name: NodeClassificationFullTrainer
_idx0
<class 'autogl.module.train.node_classification_full.NodeClassificationFullTrainer'>
---


In [64]:
encoder = v.encoder

In [65]:
encoder.hyper_parameters

{'num_layers': 2, 'hidden': [47], 'dropout': 0.772354437743668, 'act': 'elu'}

In [67]:
joblib.dump(encoder.__class__, '__class__.joblib')

['__class__.joblib']

In [71]:
joblib.dump(encoder.model, 'model.joblib')

['model.joblib']

In [73]:
encoder.model.state_dict()

OrderedDict([('_GCN__sequential_encoding_layers.0._convolution.bias',
              tensor([ 0.0604,  0.0159,  0.0130,  0.0507,  0.0272,  0.0204,  0.0408,  0.0055,
                       0.0560,  0.0350,  0.0353,  0.0571,  0.0531,  0.0193,  0.0385,  0.0012,
                       0.0253,  0.0544,  0.0338,  0.0204, -0.0114, -0.0110,  0.0539,  0.0171,
                       0.0172,  0.0174,  0.0236,  0.0258,  0.0165,  0.0072,  0.0200,  0.0148,
                      -0.0128,  0.0157,  0.0704,  0.0419,  0.0165,  0.0085,  0.0197,  0.0097,
                       0.0125, -0.0299,  0.0281,  0.0074, -0.0322,  0.0380,  0.0724])),
             ('_GCN__sequential_encoding_layers.0._convolution.lin.weight',
              tensor([[ 3.3453e-02,  1.0288e-01,  6.3909e-02,  ..., -7.5389e-02,
                        6.8808e-02, -7.8669e-02],
                      [-2.7337e-02,  1.9078e-02, -1.4864e-01,  ..., -4.1355e-02,
                        2.6141e-01, -1.1605e-01],
                      [-1.5863e-03

In [72]:
type(encoder.model)

autogl.module.model.pyg.gcn.GCN

In [42]:
repr(autoClassifier)

'<autogl.solver.classifier.node_classifier.AutoNodeClassifier object at 0x7fd87fe30c10>'

In [13]:
autoClassifier.feature_module

In [14]:

joblib.dump(autoClassifier.feature_module, 'feature_module.joblib')

['feature_module.joblib']

decoder: None
early_stopping_round: 21
encoder: <autogl.module.model.pyg.gcn.AutoGCN object at 0x7fd8ac8e3e50>
learning_rate: 0.008329372188913789
max_epoch: 139
optimizer: !!python/name:torch.optim.adam.Adam ''
trainer_name: NodeClassificationFullTrainer
_idx0
<class 'autogl.module.train.node_classification_full.NodeClassificationFullTrainer'>
---


In [51]:
v.hyper_parameters

{'max_epoch': 139,
 'early_stopping_round': 21,
 'lr': 0.008329372188913789,
 'weight_decay': 0.0003416743789200837}

In [49]:
v.duplicate_from_hyper_parameter(v.)

<bound method NodeClassificationFullTrainer.duplicate_from_hyper_parameter of decoder: None
early_stopping_round: 21
encoder: <autogl.module.model.pyg.gcn.AutoGCN object at 0x7fd8ac8e3e50>
learning_rate: 0.008329372188913789
max_epoch: 139
optimizer: !!python/name:torch.optim.adam.Adam ''
trainer_name: NodeClassificationFullTrainer
>

In [31]:
v.encoder.hyper_parameters

{'num_layers': 2, 'hidden': [47], 'dropout': 0.772354437743668, 'act': 'elu'}

In [37]:
list(autoClassifier.trained_models.keys())

["decoder: None\nearly_stopping_round: 24\nencoder: <autogl.module.model.pyg.gcn.AutoGCN object at 0x7f3b3d4e8df0>\nlearning_rate: 0.0076789463628175415\nmax_epoch: 298\noptimizer: !!python/name:torch.optim.adam.Adam ''\ntrainer_name: NodeClassificationFullTrainer\n_idx0",
 "decoder: None\nearly_stopping_round: 17\nencoder: <autogl.module.model.pyg.gcn.AutoGCN object at 0x7f3c8497c700>\nlearning_rate: 0.01266182115775376\nmax_epoch: 276\noptimizer: !!python/name:torch.optim.adam.Adam ''\ntrainer_name: NodeClassificationFullTrainer\n_idx0"]

In [22]:
bestModel = autoClassifier.get_leaderboard().get_best_model()
bestModel['encoder']

TypeError: string indices must be integers

In [10]:
import joblib